// Code generated by protoc-gen-go.
// source: vmserver.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	vmserver.proto

It has these top-level messages:
	File
	UploadResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File struct {
	Size int64  `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UploadResponse struct {
}

func (m *UploadResponse) Reset()                    { *m = UploadResponse{} }
func (m *UploadResponse) String() string            { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()               {}
func (*UploadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*File)(nil), "api.File")
	proto.RegisterType((*UploadResponse)(nil), "api.UploadResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for BulkTest service

type BulkTestClient interface {
	UploadFiles(ctx context.Context, in *File, opts ...grpc.CallOption) (*UploadResponse, error)
}

type bulkTestClient struct {
	cc *grpc.ClientConn
}

func NewBulkTestClient(cc *grpc.ClientConn) BulkTestClient {
	return &bulkTestClient{cc}
}

func (c *bulkTestClient) UploadFiles(ctx context.Context, in *File, opts ...grpc.CallOption) (*UploadResponse, error) {
	out := new(UploadResponse)
	err := grpc.Invoke(ctx, "/api.BulkTest/UploadFiles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BulkTest service

type BulkTestServer interface {
	UploadFiles(context.Context, *File) (*UploadResponse, error)
}

func RegisterBulkTestServer(s *grpc.Server, srv BulkTestServer) {
	s.RegisterService(&_BulkTest_serviceDesc, srv)
}

func _BulkTest_UploadFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BulkTestServer).UploadFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BulkTest/UploadFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BulkTestServer).UploadFiles(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

var _BulkTest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.BulkTest",
	HandlerType: (*BulkTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadFiles",
			Handler:    _BulkTest_UploadFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("vmserver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2a, 0xcd, 0xc9,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xd2, 0xe3, 0x62, 0x71,
	0xcb, 0xcc, 0x49, 0x15, 0x12, 0xe2, 0x62, 0x29, 0xce, 0xac, 0x4a, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0e, 0x02, 0xb3, 0x41, 0x62, 0x29, 0x89, 0x25, 0x89, 0x12, 0x4c, 0x40, 0x31, 0x9e, 0x20,
	0x30, 0x5b, 0x49, 0x80, 0x8b, 0x2f, 0xb4, 0x20, 0x27, 0x3f, 0x31, 0x25, 0x28, 0xb5, 0xb8, 0x20,
	0x3f, 0xaf, 0x38, 0xd5, 0xc8, 0x9a, 0x8b, 0xc3, 0x09, 0x68, 0x68, 0x48, 0x6a, 0x71, 0x89, 0x90,
	0x3e, 0x17, 0x37, 0x44, 0x16, 0x64, 0x66, 0xb1, 0x10, 0xa7, 0x1e, 0xd0, 0x0a, 0x3d, 0x10, 0x5b,
	0x4a, 0x18, 0xcc, 0x44, 0xd5, 0xaa, 0xc4, 0x90, 0xc4, 0x06, 0x76, 0x8a, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x62, 0xd6, 0x1d, 0xcc, 0x98, 0x00, 0x00, 0x00,
}
