// Code generated by protoc-gen-go.
// source: vmserver.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	vmserver.proto

It has these top-level messages:
	GetMetricsRequest
	GetMetricsResponse
	LogsRequest
	LogLine
	File
	UploadResponse
	StartProxyRequest
	StartProxyResponse
	RunCmdRequest
	RunCmdResponse
	SetIPRequest
	SetIPResponse
	GetIPRequest
	GetIPResponse
	SetSandboxConfigRequest
	SetSandboxConfigResponse
	GetSandboxConfigRequest
	GetSandboxConfigResponse
	CopyFileRequest
	CopyFileResponse
	MountFsRequest
	MountFsResponse
	SetHostnameRequest
	SetHostnameResponse
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMetricsRequest struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *GetMetricsRequest) Reset()                    { *m = GetMetricsRequest{} }
func (m *GetMetricsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMetricsRequest) ProtoMessage()               {}
func (*GetMetricsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetMetricsResponse struct {
	JsonMetricResponses [][]byte `protobuf:"bytes,1,rep,name=jsonMetricResponses,proto3" json:"jsonMetricResponses,omitempty"`
}

func (m *GetMetricsResponse) Reset()                    { *m = GetMetricsResponse{} }
func (m *GetMetricsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMetricsResponse) ProtoMessage()               {}
func (*GetMetricsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LogsRequest struct {
	ContainerID string `protobuf:"bytes,1,opt,name=containerID" json:"containerID,omitempty"`
}

func (m *LogsRequest) Reset()                    { *m = LogsRequest{} }
func (m *LogsRequest) String() string            { return proto.CompactTextString(m) }
func (*LogsRequest) ProtoMessage()               {}
func (*LogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LogLine struct {
	LogLine string `protobuf:"bytes,1,opt,name=logLine" json:"logLine,omitempty"`
}

func (m *LogLine) Reset()                    { *m = LogLine{} }
func (m *LogLine) String() string            { return proto.CompactTextString(m) }
func (*LogLine) ProtoMessage()               {}
func (*LogLine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type File struct {
	Size int64  `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type UploadResponse struct {
}

func (m *UploadResponse) Reset()                    { *m = UploadResponse{} }
func (m *UploadResponse) String() string            { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()               {}
func (*UploadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type StartProxyRequest struct {
	Ip          string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	ClusterCidr string `protobuf:"bytes,2,opt,name=clusterCidr" json:"clusterCidr,omitempty"`
	Kubeconfig  []byte `protobuf:"bytes,3,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
}

func (m *StartProxyRequest) Reset()                    { *m = StartProxyRequest{} }
func (m *StartProxyRequest) String() string            { return proto.CompactTextString(m) }
func (*StartProxyRequest) ProtoMessage()               {}
func (*StartProxyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type StartProxyResponse struct {
}

func (m *StartProxyResponse) Reset()                    { *m = StartProxyResponse{} }
func (m *StartProxyResponse) String() string            { return proto.CompactTextString(m) }
func (*StartProxyResponse) ProtoMessage()               {}
func (*StartProxyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type RunCmdRequest struct {
	Cmd  string   `protobuf:"bytes,1,opt,name=cmd" json:"cmd,omitempty"`
	Args []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
}

func (m *RunCmdRequest) Reset()                    { *m = RunCmdRequest{} }
func (m *RunCmdRequest) String() string            { return proto.CompactTextString(m) }
func (*RunCmdRequest) ProtoMessage()               {}
func (*RunCmdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type RunCmdResponse struct {
}

func (m *RunCmdResponse) Reset()                    { *m = RunCmdResponse{} }
func (m *RunCmdResponse) String() string            { return proto.CompactTextString(m) }
func (*RunCmdResponse) ProtoMessage()               {}
func (*RunCmdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SetIPRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *SetIPRequest) Reset()                    { *m = SetIPRequest{} }
func (m *SetIPRequest) String() string            { return proto.CompactTextString(m) }
func (*SetIPRequest) ProtoMessage()               {}
func (*SetIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type SetIPResponse struct {
}

func (m *SetIPResponse) Reset()                    { *m = SetIPResponse{} }
func (m *SetIPResponse) String() string            { return proto.CompactTextString(m) }
func (*SetIPResponse) ProtoMessage()               {}
func (*SetIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type GetIPRequest struct {
}

func (m *GetIPRequest) Reset()                    { *m = GetIPRequest{} }
func (m *GetIPRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIPRequest) ProtoMessage()               {}
func (*GetIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type GetIPResponse struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *GetIPResponse) Reset()                    { *m = GetIPResponse{} }
func (m *GetIPResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIPResponse) ProtoMessage()               {}
func (*GetIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type SetSandboxConfigRequest struct {
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *SetSandboxConfigRequest) Reset()                    { *m = SetSandboxConfigRequest{} }
func (m *SetSandboxConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*SetSandboxConfigRequest) ProtoMessage()               {}
func (*SetSandboxConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type SetSandboxConfigResponse struct {
}

func (m *SetSandboxConfigResponse) Reset()                    { *m = SetSandboxConfigResponse{} }
func (m *SetSandboxConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*SetSandboxConfigResponse) ProtoMessage()               {}
func (*SetSandboxConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type GetSandboxConfigRequest struct {
}

func (m *GetSandboxConfigRequest) Reset()                    { *m = GetSandboxConfigRequest{} }
func (m *GetSandboxConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSandboxConfigRequest) ProtoMessage()               {}
func (*GetSandboxConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type GetSandboxConfigResponse struct {
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *GetSandboxConfigResponse) Reset()                    { *m = GetSandboxConfigResponse{} }
func (m *GetSandboxConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSandboxConfigResponse) ProtoMessage()               {}
func (*GetSandboxConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type CopyFileRequest struct {
	File     string `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	FileData []byte `protobuf:"bytes,2,opt,name=fileData,proto3" json:"fileData,omitempty"`
}

func (m *CopyFileRequest) Reset()                    { *m = CopyFileRequest{} }
func (m *CopyFileRequest) String() string            { return proto.CompactTextString(m) }
func (*CopyFileRequest) ProtoMessage()               {}
func (*CopyFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type CopyFileResponse struct {
}

func (m *CopyFileResponse) Reset()                    { *m = CopyFileResponse{} }
func (m *CopyFileResponse) String() string            { return proto.CompactTextString(m) }
func (*CopyFileResponse) ProtoMessage()               {}
func (*CopyFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type MountFsRequest struct {
	Source   string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Target   string `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
	Fstype   string `protobuf:"bytes,3,opt,name=fstype" json:"fstype,omitempty"`
	ReadOnly bool   `protobuf:"varint,4,opt,name=readOnly" json:"readOnly,omitempty"`
}

func (m *MountFsRequest) Reset()                    { *m = MountFsRequest{} }
func (m *MountFsRequest) String() string            { return proto.CompactTextString(m) }
func (*MountFsRequest) ProtoMessage()               {}
func (*MountFsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type MountFsResponse struct {
}

func (m *MountFsResponse) Reset()                    { *m = MountFsResponse{} }
func (m *MountFsResponse) String() string            { return proto.CompactTextString(m) }
func (*MountFsResponse) ProtoMessage()               {}
func (*MountFsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type SetHostnameRequest struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
}

func (m *SetHostnameRequest) Reset()                    { *m = SetHostnameRequest{} }
func (m *SetHostnameRequest) String() string            { return proto.CompactTextString(m) }
func (*SetHostnameRequest) ProtoMessage()               {}
func (*SetHostnameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type SetHostnameResponse struct {
}

func (m *SetHostnameResponse) Reset()                    { *m = SetHostnameResponse{} }
func (m *SetHostnameResponse) String() string            { return proto.CompactTextString(m) }
func (*SetHostnameResponse) ProtoMessage()               {}
func (*SetHostnameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func init() {
	proto.RegisterType((*GetMetricsRequest)(nil), "common.GetMetricsRequest")
	proto.RegisterType((*GetMetricsResponse)(nil), "common.GetMetricsResponse")
	proto.RegisterType((*LogsRequest)(nil), "common.LogsRequest")
	proto.RegisterType((*LogLine)(nil), "common.LogLine")
	proto.RegisterType((*File)(nil), "common.File")
	proto.RegisterType((*UploadResponse)(nil), "common.UploadResponse")
	proto.RegisterType((*StartProxyRequest)(nil), "common.StartProxyRequest")
	proto.RegisterType((*StartProxyResponse)(nil), "common.StartProxyResponse")
	proto.RegisterType((*RunCmdRequest)(nil), "common.RunCmdRequest")
	proto.RegisterType((*RunCmdResponse)(nil), "common.RunCmdResponse")
	proto.RegisterType((*SetIPRequest)(nil), "common.SetIPRequest")
	proto.RegisterType((*SetIPResponse)(nil), "common.SetIPResponse")
	proto.RegisterType((*GetIPRequest)(nil), "common.GetIPRequest")
	proto.RegisterType((*GetIPResponse)(nil), "common.GetIPResponse")
	proto.RegisterType((*SetSandboxConfigRequest)(nil), "common.SetSandboxConfigRequest")
	proto.RegisterType((*SetSandboxConfigResponse)(nil), "common.SetSandboxConfigResponse")
	proto.RegisterType((*GetSandboxConfigRequest)(nil), "common.GetSandboxConfigRequest")
	proto.RegisterType((*GetSandboxConfigResponse)(nil), "common.GetSandboxConfigResponse")
	proto.RegisterType((*CopyFileRequest)(nil), "common.CopyFileRequest")
	proto.RegisterType((*CopyFileResponse)(nil), "common.CopyFileResponse")
	proto.RegisterType((*MountFsRequest)(nil), "common.MountFsRequest")
	proto.RegisterType((*MountFsResponse)(nil), "common.MountFsResponse")
	proto.RegisterType((*SetHostnameRequest)(nil), "common.SetHostnameRequest")
	proto.RegisterType((*SetHostnameResponse)(nil), "common.SetHostnameResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Metrics service

type MetricsClient interface {
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type metricsClient struct {
	cc *grpc.ClientConn
}

func NewMetricsClient(cc *grpc.ClientConn) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	out := new(GetMetricsResponse)
	err := grpc.Invoke(ctx, "/common.Metrics/GetMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Metrics service

type MetricsServer interface {
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
}

func RegisterMetricsServer(s *grpc.Server, srv MetricsServer) {
	s.RegisterService(&_Metrics_serviceDesc, srv)
}

func _Metrics_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Metrics/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metrics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetrics",
			Handler:    _Metrics_GetMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for VMServer service

type VMServerClient interface {
	// rpc UploadFiles(File) returns (UploadResponse) {}
	StartProxy(ctx context.Context, in *StartProxyRequest, opts ...grpc.CallOption) (*StartProxyResponse, error)
	RunCmd(ctx context.Context, in *RunCmdRequest, opts ...grpc.CallOption) (*RunCmdResponse, error)
	SetPodIP(ctx context.Context, in *SetIPRequest, opts ...grpc.CallOption) (*SetIPResponse, error)
	GetPodIP(ctx context.Context, in *GetIPRequest, opts ...grpc.CallOption) (*GetIPResponse, error)
	SetSandboxConfig(ctx context.Context, in *SetSandboxConfigRequest, opts ...grpc.CallOption) (*SetSandboxConfigResponse, error)
	GetSandboxConfig(ctx context.Context, in *GetSandboxConfigRequest, opts ...grpc.CallOption) (*GetSandboxConfigResponse, error)
	CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*CopyFileResponse, error)
	MountFs(ctx context.Context, in *MountFsRequest, opts ...grpc.CallOption) (*MountFsResponse, error)
	SetHostname(ctx context.Context, in *SetHostnameRequest, opts ...grpc.CallOption) (*SetHostnameResponse, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (VMServer_LogsClient, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type vMServerClient struct {
	cc *grpc.ClientConn
}

func NewVMServerClient(cc *grpc.ClientConn) VMServerClient {
	return &vMServerClient{cc}
}

func (c *vMServerClient) StartProxy(ctx context.Context, in *StartProxyRequest, opts ...grpc.CallOption) (*StartProxyResponse, error) {
	out := new(StartProxyResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/StartProxy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) RunCmd(ctx context.Context, in *RunCmdRequest, opts ...grpc.CallOption) (*RunCmdResponse, error) {
	out := new(RunCmdResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/RunCmd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) SetPodIP(ctx context.Context, in *SetIPRequest, opts ...grpc.CallOption) (*SetIPResponse, error) {
	out := new(SetIPResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/SetPodIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) GetPodIP(ctx context.Context, in *GetIPRequest, opts ...grpc.CallOption) (*GetIPResponse, error) {
	out := new(GetIPResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/GetPodIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) SetSandboxConfig(ctx context.Context, in *SetSandboxConfigRequest, opts ...grpc.CallOption) (*SetSandboxConfigResponse, error) {
	out := new(SetSandboxConfigResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/SetSandboxConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) GetSandboxConfig(ctx context.Context, in *GetSandboxConfigRequest, opts ...grpc.CallOption) (*GetSandboxConfigResponse, error) {
	out := new(GetSandboxConfigResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/GetSandboxConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*CopyFileResponse, error) {
	out := new(CopyFileResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/CopyFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) MountFs(ctx context.Context, in *MountFsRequest, opts ...grpc.CallOption) (*MountFsResponse, error) {
	out := new(MountFsResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/MountFs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) SetHostname(ctx context.Context, in *SetHostnameRequest, opts ...grpc.CallOption) (*SetHostnameResponse, error) {
	out := new(SetHostnameResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/SetHostname", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (VMServer_LogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VMServer_serviceDesc.Streams[0], c.cc, "/common.VMServer/Logs", opts...)
	if err != nil {
		return nil, err
	}
	x := &vMServerLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VMServer_LogsClient interface {
	Recv() (*LogLine, error)
	grpc.ClientStream
}

type vMServerLogsClient struct {
	grpc.ClientStream
}

func (x *vMServerLogsClient) Recv() (*LogLine, error) {
	m := new(LogLine)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vMServerClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	out := new(GetMetricsResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/GetMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VMServer service

type VMServerServer interface {
	// rpc UploadFiles(File) returns (UploadResponse) {}
	StartProxy(context.Context, *StartProxyRequest) (*StartProxyResponse, error)
	RunCmd(context.Context, *RunCmdRequest) (*RunCmdResponse, error)
	SetPodIP(context.Context, *SetIPRequest) (*SetIPResponse, error)
	GetPodIP(context.Context, *GetIPRequest) (*GetIPResponse, error)
	SetSandboxConfig(context.Context, *SetSandboxConfigRequest) (*SetSandboxConfigResponse, error)
	GetSandboxConfig(context.Context, *GetSandboxConfigRequest) (*GetSandboxConfigResponse, error)
	CopyFile(context.Context, *CopyFileRequest) (*CopyFileResponse, error)
	MountFs(context.Context, *MountFsRequest) (*MountFsResponse, error)
	SetHostname(context.Context, *SetHostnameRequest) (*SetHostnameResponse, error)
	Logs(*LogsRequest, VMServer_LogsServer) error
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
}

func RegisterVMServerServer(s *grpc.Server, srv VMServerServer) {
	s.RegisterService(&_VMServer_serviceDesc, srv)
}

func _VMServer_StartProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).StartProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/StartProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).StartProxy(ctx, req.(*StartProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_RunCmd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).RunCmd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/RunCmd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).RunCmd(ctx, req.(*RunCmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_SetPodIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).SetPodIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/SetPodIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).SetPodIP(ctx, req.(*SetIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_GetPodIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).GetPodIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/GetPodIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).GetPodIP(ctx, req.(*GetIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_SetSandboxConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSandboxConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).SetSandboxConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/SetSandboxConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).SetSandboxConfig(ctx, req.(*SetSandboxConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_GetSandboxConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).GetSandboxConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/GetSandboxConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).GetSandboxConfig(ctx, req.(*GetSandboxConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_CopyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).CopyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/CopyFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).CopyFile(ctx, req.(*CopyFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_MountFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountFsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).MountFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/MountFs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).MountFs(ctx, req.(*MountFsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_SetHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHostnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).SetHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/SetHostname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).SetHostname(ctx, req.(*SetHostnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMServerServer).Logs(m, &vMServerLogsServer{stream})
}

type VMServer_LogsServer interface {
	Send(*LogLine) error
	grpc.ServerStream
}

type vMServerLogsServer struct {
	grpc.ServerStream
}

func (x *vMServerLogsServer) Send(m *LogLine) error {
	return x.ServerStream.SendMsg(m)
}

func _VMServer_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VMServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.VMServer",
	HandlerType: (*VMServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProxy",
			Handler:    _VMServer_StartProxy_Handler,
		},
		{
			MethodName: "RunCmd",
			Handler:    _VMServer_RunCmd_Handler,
		},
		{
			MethodName: "SetPodIP",
			Handler:    _VMServer_SetPodIP_Handler,
		},
		{
			MethodName: "GetPodIP",
			Handler:    _VMServer_GetPodIP_Handler,
		},
		{
			MethodName: "SetSandboxConfig",
			Handler:    _VMServer_SetSandboxConfig_Handler,
		},
		{
			MethodName: "GetSandboxConfig",
			Handler:    _VMServer_GetSandboxConfig_Handler,
		},
		{
			MethodName: "CopyFile",
			Handler:    _VMServer_CopyFile_Handler,
		},
		{
			MethodName: "MountFs",
			Handler:    _VMServer_MountFs_Handler,
		},
		{
			MethodName: "SetHostname",
			Handler:    _VMServer_SetHostname_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _VMServer_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _VMServer_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("vmserver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 707 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0xdf, 0x6f, 0xda, 0x3a,
	0x14, 0x2e, 0x85, 0x52, 0xee, 0x29, 0x05, 0xea, 0xfe, 0x20, 0xcd, 0x95, 0xda, 0xca, 0xf7, 0xa5,
	0xf7, 0x85, 0xb1, 0x4e, 0x7b, 0x98, 0x34, 0x69, 0x9a, 0xe8, 0x9a, 0x56, 0x6a, 0x35, 0x14, 0xb4,
	0xed, 0x39, 0x25, 0x2e, 0xcb, 0x06, 0x31, 0x8b, 0x4d, 0x55, 0xf6, 0x87, 0xef, 0x79, 0xb6, 0x63,
	0x27, 0x2e, 0x09, 0xda, 0xcb, 0x9e, 0xf0, 0xf9, 0x7c, 0xce, 0xf7, 0x9d, 0x43, 0xbe, 0x93, 0x40,
	0xeb, 0x71, 0xc6, 0x48, 0xf2, 0x48, 0x92, 0xde, 0x3c, 0xa1, 0x9c, 0xa2, 0xfa, 0x98, 0xce, 0x66,
	0x34, 0xc6, 0xff, 0xc3, 0x9e, 0x47, 0xf8, 0x1d, 0xe1, 0x49, 0x34, 0x66, 0x3e, 0xf9, 0xb1, 0x20,
	0x8c, 0xa3, 0x03, 0xd8, 0x1a, 0xd3, 0x45, 0xcc, 0x9d, 0xca, 0x59, 0xe5, 0x7c, 0xcb, 0x4f, 0x03,
	0x7c, 0x05, 0xc8, 0x4e, 0x65, 0x73, 0x1a, 0x33, 0x82, 0xfa, 0xb0, 0xff, 0x8d, 0xd1, 0x38, 0x85,
	0x0d, 0xca, 0x44, 0x65, 0xf5, 0xbc, 0xe9, 0x97, 0x5d, 0xe1, 0x17, 0xb0, 0x73, 0x4b, 0x27, 0x99,
	0xd8, 0x19, 0xec, 0x8c, 0x69, 0xcc, 0x83, 0x28, 0x26, 0xc9, 0xcd, 0xa5, 0x92, 0xfc, 0xc7, 0xb7,
	0x21, 0xfc, 0x1f, 0x6c, 0x8b, 0x82, 0x5b, 0x11, 0x21, 0x07, 0xb6, 0xa7, 0xe9, 0x51, 0x27, 0x9a,
	0x10, 0xf7, 0xa0, 0x76, 0x15, 0x4d, 0x09, 0x42, 0x50, 0x63, 0xd1, 0xcf, 0xf4, 0xba, 0xea, 0xab,
	0xb3, 0xc4, 0xc2, 0x80, 0x07, 0xce, 0xa6, 0xc0, 0x9a, 0xbe, 0x3a, 0xe3, 0x0e, 0xb4, 0x3e, 0xcd,
	0xa7, 0x34, 0x08, 0x4d, 0x63, 0x98, 0xc0, 0xde, 0x88, 0x07, 0x09, 0x1f, 0x26, 0xf4, 0x69, 0x69,
	0xba, 0x6b, 0xc1, 0x66, 0x34, 0xd7, 0x5a, 0xe2, 0xa4, 0xba, 0x9d, 0x2e, 0x18, 0x27, 0xc9, 0x20,
	0x0a, 0x13, 0xc5, 0x28, 0xbb, 0xcd, 0x21, 0x74, 0x02, 0xf0, 0x7d, 0x71, 0x4f, 0xc4, 0x00, 0x0f,
	0xd1, 0xc4, 0xa9, 0x2a, 0x49, 0x0b, 0xc1, 0x07, 0x80, 0x6c, 0x19, 0x2d, 0xfe, 0x1a, 0x76, 0xfd,
	0x45, 0x3c, 0x98, 0x85, 0x46, 0xb8, 0x03, 0xd5, 0xf1, 0x2c, 0xd4, 0xca, 0xf2, 0x28, 0xa7, 0x08,
	0x92, 0x09, 0x13, 0x9a, 0x55, 0x01, 0xa9, 0xb3, 0x9c, 0xc2, 0x94, 0x69, 0xa2, 0x13, 0x68, 0x8e,
	0x08, 0xbf, 0x19, 0xae, 0x19, 0x00, 0xb7, 0x61, 0x57, 0xdf, 0xeb, 0x82, 0x16, 0x34, 0x3d, 0xab,
	0x00, 0x9f, 0xc2, 0xae, 0x67, 0x27, 0x14, 0x18, 0x5e, 0x42, 0x57, 0x30, 0x8c, 0x82, 0x38, 0xbc,
	0xa7, 0x4f, 0x03, 0x35, 0x94, 0x11, 0x3b, 0x82, 0xba, 0x9e, 0xbb, 0xa2, 0xe6, 0xd6, 0x11, 0x76,
	0xc1, 0x29, 0x96, 0x68, 0xfd, 0x63, 0xe8, 0x7a, 0xe5, 0x74, 0xf8, 0x02, 0x1c, 0x6f, 0x4d, 0xd9,
	0x5a, 0xa9, 0xf7, 0xd0, 0x1e, 0xd0, 0xf9, 0x52, 0x7a, 0xc1, 0x74, 0x25, 0xfe, 0xb8, 0x07, 0x11,
	0xea, 0x11, 0xd4, 0x19, 0xb9, 0xd0, 0x90, 0xbf, 0x97, 0xb9, 0x2d, 0xb2, 0x18, 0x23, 0xe8, 0xe4,
	0x14, 0xba, 0x4b, 0x0e, 0xad, 0x3b, 0xb9, 0x05, 0x57, 0xcc, 0x9a, 0x95, 0xd1, 0x45, 0x32, 0x36,
	0xbc, 0x3a, 0x92, 0xb8, 0x78, 0xbc, 0x13, 0xc2, 0xb5, 0x39, 0x74, 0x24, 0xf1, 0x07, 0xc6, 0x97,
	0x73, 0xa2, 0x3c, 0x21, 0xf0, 0x34, 0x92, 0x9d, 0x24, 0x24, 0x08, 0x3f, 0xc6, 0xd3, 0xa5, 0x53,
	0x13, 0x37, 0x0d, 0x3f, 0x8b, 0xf1, 0x1e, 0xb4, 0x33, 0x55, 0xdd, 0x48, 0x5f, 0xd8, 0x87, 0xf0,
	0x6b, 0xca, 0x78, 0x1c, 0xcc, 0xb2, 0x11, 0x05, 0xc9, 0x57, 0x0d, 0xe9, 0x76, 0xb2, 0x18, 0x1f,
	0xc2, 0xfe, 0xb3, 0x8a, 0x94, 0xe8, 0x62, 0x08, 0xdb, 0x7a, 0x97, 0xd1, 0x07, 0x80, 0x7c, 0xb3,
	0xd1, 0x71, 0x2f, 0x7d, 0x37, 0xf4, 0x0a, 0x2f, 0x06, 0xd7, 0x2d, 0xbb, 0xd2, 0x8d, 0x6d, 0x5c,
	0xfc, 0xda, 0x82, 0xc6, 0xe7, 0xbb, 0x91, 0x7a, 0xcd, 0x48, 0xce, 0xdc, 0xe6, 0x39, 0x67, 0x61,
	0xc3, 0x72, 0xce, 0x92, 0xad, 0xd8, 0x40, 0x6f, 0xa0, 0x9e, 0x1a, 0x1c, 0x1d, 0x9a, 0xbc, 0x67,
	0x7b, 0xe2, 0x1e, 0xad, 0xc2, 0x56, 0x69, 0x43, 0xcc, 0x3d, 0xa4, 0xe1, 0xcd, 0x10, 0x1d, 0x64,
	0x22, 0x96, 0xd5, 0xdd, 0xc3, 0x15, 0xd4, 0x2e, 0xf5, 0x0a, 0xa5, 0x5e, 0x69, 0xa9, 0xb7, 0x52,
	0xfa, 0x05, 0x3a, 0xab, 0x56, 0x47, 0xa7, 0x96, 0x4e, 0x99, 0xd1, 0xdd, 0xb3, 0xf5, 0x09, 0x36,
	0xb1, 0xb7, 0x96, 0xd8, 0xfb, 0x13, 0xb1, 0xb7, 0x9e, 0xf8, 0x1d, 0x34, 0x8c, 0xdd, 0x51, 0xd7,
	0xe4, 0xaf, 0xec, 0x90, 0xeb, 0x14, 0x2f, 0x32, 0x82, 0xb7, 0xc2, 0x49, 0xa9, 0x4b, 0x51, 0xf6,
	0x34, 0x9e, 0x2f, 0x8b, 0xdb, 0x2d, 0xe0, 0x59, 0xf5, 0x35, 0xec, 0x58, 0xf6, 0x44, 0xae, 0xf5,
	0x57, 0xac, 0xb8, 0xdc, 0xfd, 0xb7, 0xf4, 0x2e, 0x63, 0xea, 0x43, 0x4d, 0x7e, 0x58, 0xd0, 0xbe,
	0x49, 0xb3, 0x3e, 0x33, 0x6e, 0xdb, 0x02, 0xd5, 0x07, 0x63, 0xa3, 0x5f, 0xf9, 0x4b, 0xc6, 0xbf,
	0xaf, 0xab, 0x6f, 0xea, 0xab, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x76, 0xa6, 0xae, 0x44, 0x65,
	0x07, 0x00, 0x00,
}
