// Code generated by protoc-gen-go.
// source: vmserver.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	vmserver.proto

It has these top-level messages:
	File
	UploadResponse
	StartProxyRequest
	StartProxyResponse
	RunCmdRequest
	RunCmdResponse
	SetIPRequest
	SetIPResponse
	GetIPRequest
	GetIPResponse
	SetSandboxConfigRequest
	SetSandboxConfigResponse
	GetSandboxConfigRequest
	GetSandboxConfigResponse
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File struct {
	Size int64  `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UploadResponse struct {
}

func (m *UploadResponse) Reset()                    { *m = UploadResponse{} }
func (m *UploadResponse) String() string            { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()               {}
func (*UploadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StartProxyRequest struct {
	Ip          string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	ClusterCidr string `protobuf:"bytes,2,opt,name=clusterCidr" json:"clusterCidr,omitempty"`
	Kubeconfig  []byte `protobuf:"bytes,3,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
}

func (m *StartProxyRequest) Reset()                    { *m = StartProxyRequest{} }
func (m *StartProxyRequest) String() string            { return proto.CompactTextString(m) }
func (*StartProxyRequest) ProtoMessage()               {}
func (*StartProxyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StartProxyResponse struct {
}

func (m *StartProxyResponse) Reset()                    { *m = StartProxyResponse{} }
func (m *StartProxyResponse) String() string            { return proto.CompactTextString(m) }
func (*StartProxyResponse) ProtoMessage()               {}
func (*StartProxyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RunCmdRequest struct {
	Cmd  string   `protobuf:"bytes,1,opt,name=cmd" json:"cmd,omitempty"`
	Args []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
}

func (m *RunCmdRequest) Reset()                    { *m = RunCmdRequest{} }
func (m *RunCmdRequest) String() string            { return proto.CompactTextString(m) }
func (*RunCmdRequest) ProtoMessage()               {}
func (*RunCmdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type RunCmdResponse struct {
}

func (m *RunCmdResponse) Reset()                    { *m = RunCmdResponse{} }
func (m *RunCmdResponse) String() string            { return proto.CompactTextString(m) }
func (*RunCmdResponse) ProtoMessage()               {}
func (*RunCmdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SetIPRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *SetIPRequest) Reset()                    { *m = SetIPRequest{} }
func (m *SetIPRequest) String() string            { return proto.CompactTextString(m) }
func (*SetIPRequest) ProtoMessage()               {}
func (*SetIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type SetIPResponse struct {
}

func (m *SetIPResponse) Reset()                    { *m = SetIPResponse{} }
func (m *SetIPResponse) String() string            { return proto.CompactTextString(m) }
func (*SetIPResponse) ProtoMessage()               {}
func (*SetIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetIPRequest struct {
}

func (m *GetIPRequest) Reset()                    { *m = GetIPRequest{} }
func (m *GetIPRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIPRequest) ProtoMessage()               {}
func (*GetIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type GetIPResponse struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *GetIPResponse) Reset()                    { *m = GetIPResponse{} }
func (m *GetIPResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIPResponse) ProtoMessage()               {}
func (*GetIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SetSandboxConfigRequest struct {
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *SetSandboxConfigRequest) Reset()                    { *m = SetSandboxConfigRequest{} }
func (m *SetSandboxConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*SetSandboxConfigRequest) ProtoMessage()               {}
func (*SetSandboxConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type SetSandboxConfigResponse struct {
}

func (m *SetSandboxConfigResponse) Reset()                    { *m = SetSandboxConfigResponse{} }
func (m *SetSandboxConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*SetSandboxConfigResponse) ProtoMessage()               {}
func (*SetSandboxConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type GetSandboxConfigRequest struct {
}

func (m *GetSandboxConfigRequest) Reset()                    { *m = GetSandboxConfigRequest{} }
func (m *GetSandboxConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSandboxConfigRequest) ProtoMessage()               {}
func (*GetSandboxConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type GetSandboxConfigResponse struct {
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *GetSandboxConfigResponse) Reset()                    { *m = GetSandboxConfigResponse{} }
func (m *GetSandboxConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSandboxConfigResponse) ProtoMessage()               {}
func (*GetSandboxConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func init() {
	proto.RegisterType((*File)(nil), "common.File")
	proto.RegisterType((*UploadResponse)(nil), "common.UploadResponse")
	proto.RegisterType((*StartProxyRequest)(nil), "common.StartProxyRequest")
	proto.RegisterType((*StartProxyResponse)(nil), "common.StartProxyResponse")
	proto.RegisterType((*RunCmdRequest)(nil), "common.RunCmdRequest")
	proto.RegisterType((*RunCmdResponse)(nil), "common.RunCmdResponse")
	proto.RegisterType((*SetIPRequest)(nil), "common.SetIPRequest")
	proto.RegisterType((*SetIPResponse)(nil), "common.SetIPResponse")
	proto.RegisterType((*GetIPRequest)(nil), "common.GetIPRequest")
	proto.RegisterType((*GetIPResponse)(nil), "common.GetIPResponse")
	proto.RegisterType((*SetSandboxConfigRequest)(nil), "common.SetSandboxConfigRequest")
	proto.RegisterType((*SetSandboxConfigResponse)(nil), "common.SetSandboxConfigResponse")
	proto.RegisterType((*GetSandboxConfigRequest)(nil), "common.GetSandboxConfigRequest")
	proto.RegisterType((*GetSandboxConfigResponse)(nil), "common.GetSandboxConfigResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for VMServer service

type VMServerClient interface {
	// rpc UploadFiles(File) returns (UploadResponse) {}
	StartProxy(ctx context.Context, in *StartProxyRequest, opts ...grpc.CallOption) (*StartProxyResponse, error)
	RunCmd(ctx context.Context, in *RunCmdRequest, opts ...grpc.CallOption) (*RunCmdResponse, error)
	SetPodIP(ctx context.Context, in *SetIPRequest, opts ...grpc.CallOption) (*SetIPResponse, error)
	GetPodIP(ctx context.Context, in *GetIPRequest, opts ...grpc.CallOption) (*GetIPResponse, error)
	SetSandboxConfig(ctx context.Context, in *SetSandboxConfigRequest, opts ...grpc.CallOption) (*SetSandboxConfigResponse, error)
	GetSandboxConfig(ctx context.Context, in *GetSandboxConfigRequest, opts ...grpc.CallOption) (*GetSandboxConfigResponse, error)
}

type vMServerClient struct {
	cc *grpc.ClientConn
}

func NewVMServerClient(cc *grpc.ClientConn) VMServerClient {
	return &vMServerClient{cc}
}

func (c *vMServerClient) StartProxy(ctx context.Context, in *StartProxyRequest, opts ...grpc.CallOption) (*StartProxyResponse, error) {
	out := new(StartProxyResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/StartProxy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) RunCmd(ctx context.Context, in *RunCmdRequest, opts ...grpc.CallOption) (*RunCmdResponse, error) {
	out := new(RunCmdResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/RunCmd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) SetPodIP(ctx context.Context, in *SetIPRequest, opts ...grpc.CallOption) (*SetIPResponse, error) {
	out := new(SetIPResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/SetPodIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) GetPodIP(ctx context.Context, in *GetIPRequest, opts ...grpc.CallOption) (*GetIPResponse, error) {
	out := new(GetIPResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/GetPodIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) SetSandboxConfig(ctx context.Context, in *SetSandboxConfigRequest, opts ...grpc.CallOption) (*SetSandboxConfigResponse, error) {
	out := new(SetSandboxConfigResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/SetSandboxConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServerClient) GetSandboxConfig(ctx context.Context, in *GetSandboxConfigRequest, opts ...grpc.CallOption) (*GetSandboxConfigResponse, error) {
	out := new(GetSandboxConfigResponse)
	err := grpc.Invoke(ctx, "/common.VMServer/GetSandboxConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VMServer service

type VMServerServer interface {
	// rpc UploadFiles(File) returns (UploadResponse) {}
	StartProxy(context.Context, *StartProxyRequest) (*StartProxyResponse, error)
	RunCmd(context.Context, *RunCmdRequest) (*RunCmdResponse, error)
	SetPodIP(context.Context, *SetIPRequest) (*SetIPResponse, error)
	GetPodIP(context.Context, *GetIPRequest) (*GetIPResponse, error)
	SetSandboxConfig(context.Context, *SetSandboxConfigRequest) (*SetSandboxConfigResponse, error)
	GetSandboxConfig(context.Context, *GetSandboxConfigRequest) (*GetSandboxConfigResponse, error)
}

func RegisterVMServerServer(s *grpc.Server, srv VMServerServer) {
	s.RegisterService(&_VMServer_serviceDesc, srv)
}

func _VMServer_StartProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).StartProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/StartProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).StartProxy(ctx, req.(*StartProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_RunCmd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).RunCmd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/RunCmd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).RunCmd(ctx, req.(*RunCmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_SetPodIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).SetPodIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/SetPodIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).SetPodIP(ctx, req.(*SetIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_GetPodIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).GetPodIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/GetPodIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).GetPodIP(ctx, req.(*GetIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_SetSandboxConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSandboxConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).SetSandboxConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/SetSandboxConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).SetSandboxConfig(ctx, req.(*SetSandboxConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMServer_GetSandboxConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServerServer).GetSandboxConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.VMServer/GetSandboxConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServerServer).GetSandboxConfig(ctx, req.(*GetSandboxConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VMServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.VMServer",
	HandlerType: (*VMServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProxy",
			Handler:    _VMServer_StartProxy_Handler,
		},
		{
			MethodName: "RunCmd",
			Handler:    _VMServer_RunCmd_Handler,
		},
		{
			MethodName: "SetPodIP",
			Handler:    _VMServer_SetPodIP_Handler,
		},
		{
			MethodName: "GetPodIP",
			Handler:    _VMServer_GetPodIP_Handler,
		},
		{
			MethodName: "SetSandboxConfig",
			Handler:    _VMServer_SetSandboxConfig_Handler,
		},
		{
			MethodName: "GetSandboxConfig",
			Handler:    _VMServer_GetSandboxConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("vmserver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0x4d, 0xcf, 0xd2, 0x40,
	0x18, 0x14, 0x4a, 0x1a, 0x78, 0x84, 0x8a, 0x1b, 0x3e, 0x4a, 0x0f, 0x40, 0xf6, 0xe4, 0xa9, 0x89,
	0x18, 0x0f, 0x9e, 0x89, 0x6e, 0x38, 0x98, 0x34, 0x6d, 0xd4, 0x73, 0x69, 0x57, 0xd2, 0x48, 0xbb,
	0x75, 0xdb, 0x12, 0xf4, 0x77, 0xf9, 0x03, 0x6d, 0x97, 0xad, 0xee, 0xdb, 0x8f, 0xbc, 0xb7, 0x87,
	0xd9, 0x67, 0x66, 0x98, 0xd9, 0x2d, 0x18, 0xb7, 0x38, 0xa3, 0xfc, 0x46, 0xb9, 0x9d, 0x72, 0x96,
	0x33, 0xa4, 0x07, 0x2c, 0x8e, 0x59, 0x82, 0x6d, 0x18, 0x7d, 0x8a, 0xae, 0x14, 0x21, 0x18, 0x65,
	0xd1, 0x6f, 0x6a, 0x0e, 0xf6, 0x83, 0x37, 0x9a, 0x2b, 0xe6, 0x0a, 0x0b, 0xfd, 0xdc, 0x37, 0x87,
	0x25, 0x36, 0x75, 0xc5, 0x8c, 0xe7, 0x60, 0x7c, 0x49, 0xaf, 0xcc, 0x0f, 0x5d, 0x9a, 0xa5, 0x2c,
	0xc9, 0x28, 0xa6, 0xf0, 0xda, 0xcb, 0x7d, 0x9e, 0x3b, 0x9c, 0xdd, 0x7f, 0xb9, 0xf4, 0x67, 0x41,
	0xb3, 0x1c, 0x19, 0x30, 0x8c, 0x52, 0x21, 0x36, 0x71, 0xcb, 0x09, 0xed, 0xe1, 0x65, 0x70, 0x2d,
	0xb2, 0x9c, 0xf2, 0x63, 0x14, 0x72, 0xa1, 0x38, 0x71, 0x55, 0x08, 0x6d, 0x01, 0x7e, 0x14, 0x67,
	0x1a, 0xb0, 0xe4, 0x7b, 0x74, 0x31, 0x35, 0x61, 0xa9, 0x20, 0x78, 0x01, 0x48, 0xb5, 0x91, 0xe6,
	0xef, 0x61, 0xe6, 0x16, 0xc9, 0x31, 0x0e, 0x6b, 0xe3, 0x39, 0x68, 0x41, 0x1c, 0x4a, 0xe7, 0x6a,
	0xac, 0x52, 0xf8, 0xfc, 0x92, 0x95, 0x9e, 0x5a, 0x09, 0x89, 0xb9, 0x4a, 0x51, 0xd3, 0xa4, 0xd0,
	0x16, 0xa6, 0x1e, 0xcd, 0x4f, 0x4e, 0x4f, 0x00, 0xfc, 0x0a, 0x66, 0xf2, 0x5c, 0x12, 0x0c, 0x98,
	0x12, 0x85, 0x80, 0x77, 0x30, 0x23, 0xea, 0x42, 0x4b, 0xe1, 0x2d, 0xac, 0x4b, 0x05, 0xcf, 0x4f,
	0xc2, 0x33, 0xbb, 0x1f, 0x45, 0xa8, 0xda, 0x6c, 0x05, 0xba, 0xcc, 0x3d, 0x10, 0xb9, 0xe5, 0x2f,
	0x6c, 0x81, 0xd9, 0xa6, 0x48, 0xff, 0x0d, 0xac, 0x49, 0xb7, 0x1c, 0x3e, 0x80, 0x49, 0x7a, 0x68,
	0x7d, 0x56, 0x87, 0x3f, 0x1a, 0x8c, 0xbf, 0x7e, 0xf6, 0xc4, 0x13, 0x41, 0x1f, 0x01, 0xfe, 0x77,
	0x8d, 0x36, 0xf6, 0xe3, 0xad, 0xd8, 0xad, 0x6b, 0xb6, 0xac, 0xae, 0x23, 0xf9, 0x07, 0x5f, 0xa0,
	0x0f, 0xa0, 0x3f, 0x5a, 0x46, 0xcb, 0x7a, 0xef, 0xc9, 0x65, 0x59, 0xab, 0x26, 0xac, 0x50, 0xc7,
	0x65, 0x72, 0x87, 0x85, 0x27, 0x07, 0x2d, 0xfe, 0x99, 0x28, 0x7d, 0x5b, 0xcb, 0x06, 0xaa, 0x52,
	0x49, 0x8b, 0x4a, 0x3a, 0xa9, 0xa4, 0x41, 0xfd, 0x06, 0xf3, 0x66, 0xdf, 0x68, 0xa7, 0xf8, 0x74,
	0xb5, 0x6d, 0xed, 0xfb, 0x17, 0x54, 0x61, 0xd2, 0x2b, 0x4c, 0x9e, 0x13, 0x26, 0xbd, 0xc2, 0x67,
	0x5d, 0x7c, 0xcd, 0xef, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x76, 0xce, 0x91, 0xdf, 0x03,
	0x00, 0x00,
}
